name: ireal

x-var: &VIRTUAL_HOST "ireal.kdl.kcl.ac.uk,localhost,127.0.0.1"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.4
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - 8000
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: *VIRTUAL_HOST
      VIRTUAL_PATH: "/"
      VIRTUAL_PROTO: "http"
      VIRTUAL_PORT: 8000
    depends_on:
      - qdrant
      - redis
      - phoenix

  qdrant:
    image: qdrant/qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - 6333
      - 6334
      - 6335
    volumes:
      - ./data/2_final/qdrant:/qdrant/storage:z

  redis:
    image: redis/redis-stack
    restart: unless-stopped
    expose:
      - 6379
      - 8001
    volumes:
      - ./data/1_interim/redis:/data

  phoenix:
    image: arizephoenix/phoenix:latest
    restart: unless-stopped
    ports:
      - "6006:6006"
      - "4317:4317"
